# Generated by Django 4.0.4 on 2022-04-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstacionamentoCarros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vagas',
            new_name='Vaga',
        ),
        migrations.AlterField(
            model_name='carro',
            name='anofabricado',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='carro',
            name='anomodelo',
            field=models.CharField(max_length=30),
        ),
    ]
